// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdq2okrgi6E4ciinl9zpFzkBWOYuSP1UQ',
    appId: '1:681096760219:web:1585c2f238fbe533fbef3e',
    messagingSenderId: '681096760219',
    projectId: 'cdc-iitram',
    authDomain: 'cdc-iitram.firebaseapp.com',
    storageBucket: 'cdc-iitram.appspot.com',
    measurementId: 'G-Q21H1CHLDT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI5PMcUTHYDPLKQzld70rnU2w-Vnc4s7E',
    appId: '1:681096760219:android:2af616970db592aafbef3e',
    messagingSenderId: '681096760219',
    projectId: 'cdc-iitram',
    storageBucket: 'cdc-iitram.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRarnHPbNhwJinzXIjMj66-jNcRbwPty0',
    appId: '1:681096760219:ios:c16c44bf64522665fbef3e',
    messagingSenderId: '681096760219',
    projectId: 'cdc-iitram',
    storageBucket: 'cdc-iitram.appspot.com',
    iosBundleId: 'com.example.cdcIitram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRarnHPbNhwJinzXIjMj66-jNcRbwPty0',
    appId: '1:681096760219:ios:3bcaa368d41cd96ffbef3e',
    messagingSenderId: '681096760219',
    projectId: 'cdc-iitram',
    storageBucket: 'cdc-iitram.appspot.com',
    iosBundleId: 'com.example.cdcIitram.RunnerTests',
  );
}
